import 'package:build_cli_annotations/build_cli_annotations.dart';

part 'options.g.dart';

/// The command line argument parser generated by the `build_cli_annotations`
/// package.
ArgParser get parser => _$populateOptionsParser(ArgParser(usageLineLength: 80));

/// The command line options for sc
@CliOptions()
class Options {
  @CliOption(abbr: 'h', negatable: false, help: 'Prints usage information.')
  final bool help;

  @CliOption(
      abbr: 'c',
      name: 'config-directory',
      help:
          'Base directory to store configuration and caches. Defaults to ~/.config/shortcut-cli. Override here or with SHORTCUT_CONFIG_DIR environment variable.')
  String? baseConfigDir;

  @CliOption(
      abbr: 'e',
      name: 'eval',
      help: 'Evaluate a one-off Shortcut program and exit.')
  late String? program;

  @CliOption(
      abbr: 'l',
      name: 'load',
      help: 'Load one or more source files at startup.')
  late List<String>? loadFiles;

  @CliOption(
      abbr: 'r',
      name: 'repl',
      negatable: false,
      help: 'Start a Shortcut REPL.',
      defaultsTo: false)
  final bool isReplMode;

  @CliOption(
      abbr: 'a',
      name: 'ansi-color',
      help:
          'Whether or not to use ANSI codes for colored output. This flag is only partially honored at this time, with ANSI printing for the majority of functions.')
  bool? isAnsiEnabled;

  Options(this.help, this.isReplMode);
}
